---
title: "p8105_hw3_fw2334"
author: "Frances Williams"
date: "10/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Problem 1
```{r}
library(p8105.datasets)
data("instacart") 
```

```{r}
aisle_df = instacart %>% 
  group_by(aisle) %>% 
  summarize(item_count = n()) %>% 
  arrange(desc(item_count))
```

There are `r nrow(aisle_df)` aisles. The most items are ordered from `fresh vegetables` and `fresh fruits`.

```{r fig.height = 10}
aisle_plot = aisle_df %>%
  filter(item_count >= 10000) %>% 
  mutate(aisle = fct_reorder(aisle, item_count)) %>% 
  ggplot(aes(x = aisle, y = item_count)) +
    geom_bar(stat = "identity") +
    coord_flip()

aisle_plot
```

### Table
```{r}
aisles_table = instacart %>%
  filter(aisle == c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  group_by(aisle, product_name) %>% 
  summarize(product_name_count = n()) %>% 
  mutate(product_rank = min_rank(-product_name_count)) %>% 
  filter(product_rank <= 3) %>% 
  mutate(product_info = paste(product_name, product_name_count, sep = ", n = ")) %>% 
  select(-product_name, -product_name_count) %>% 
  pivot_wider(
    names_from = aisle,
    values_from = product_info)

knitr::kable(aisles_table)
```

### Pink Lady Apples and Coffee Ice Cream
```{r}
apples_icecream_table = instacart %>% 
  select(product_name, order_dow, order_hour_of_day) %>% 
  filter(product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream") %>% 
  group_by(product_name, order_dow) %>% 
  mutate(mean_hour = mean(order_hour_of_day)) %>% 
  select(-order_hour_of_day) %>% 
  distinct() %>% 
  pivot_wider(
    names_from = product_name,
    values_from = mean_hour)

knitr::kable(apples_icecream_table)
```

# Problem 2
```{r}
data("brfss_smart2010")

brfss_cleaned = brfss_smart2010 %>% 
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>% 
  mutate(
    state = locationabbr,
    response_f = as.factor(response),
    response_ordered = ordered(response_f, levels = c("Poor", "Fair", "Good", "Very good", "Excellent")))
  
```

### States at 7 or more locations
```{r}

```


```{r}
brfss_excellent = brfss_cleaned %>% 
  filter(response == "Excellent") %>% 
  select(year, state, data_value) %>% 
  group_by(year, state) %>% 
  summarize(mean_value = mean(data_value, na.rm = TRUE)) %>%
  ggplot(aes(x = year, y = mean_value, group = state, color = state)) +
    geom_line()

brfss_excellent
```

```{r}
brfss_ny = brfss_cleaned %>% 
  filter(
    state == "NY",
    year == "2006" | year == "2010") %>% 
  select(year, state, response_ordered, data_value) %>% 
  group_by(year, response_ordered) %>% 
  ggplot(aes(x = response_ordered, y = data_value)) +
    geom_point() +
    facet_grid(~year)

brfss_ny
```

# Problem 3

```{r}
accel_df = read_csv(file = "./data/accel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    day_type = ifelse(day == "Saturday" | day == "Sunday", "weekend", "weekday"),
    day_f = as.factor(day),
    day_ordered = ordered(
      day_f, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")))
```

This dataset has `r nrow(accel_df)` observations. 

```{r}
accel_total = accel_df %>% 
  mutate(total_activity = 
           select(., activity_1:activity_1440) %>% 
           rowSums(na.rm = TRUE)) %>% 
  select(day_ordered, total_activity)  %>% 
  group_by(day_ordered) %>% 
  summarize(total_activity = sum(total_activity))

knitr::kable(accel_total)
```


```{r}
accel_24hr = accel_df %>% 
  select(day_ordered, activity_1:activity_1440) %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "minute_in_day",
    values_to = "activity_time") %>% 
  ggplot(aes(x = minute_in_day, y = activity_time, group = day_ordered, color = day_ordered)) +
    geom_point()

accel_24hr
```

