p8105\_hw3\_fw2334
================
Frances Williams
10/7/2019

# Problem 1

``` r
library(p8105.datasets)
data("instacart") 
```

#### Description of dataset

The `instacart` dataset includes information regarding online grocery
orders in 2017. There are 1384617 observations in the dataset, each row
being a product ordered, and there are 131209 unique users. The dataset
has 15 variables, including `days_since_prior_order`, `product_name`,
`aisle` where the product is from, and `reordered`, which indicates if
the user has previously ordered the product. An example: order ID \#1
refers to an order of Bulgarian Yogurt, Organic 4% Milk Fat Whole Milk
Cottage Cheese, Organic Celery Hearts, Cucumber Kirby, Lightly Smoked
Sardines in Olive Oil, Bag of Organic Bananas, Organic Hass Avocado,
Organic Whole String Cheese. The variable `days_since_prior_order` = 9,
indicating that this user last ordered groceries on instacart nine days
ago.

``` r
aisle_df = instacart %>% 
  group_by(aisle) %>% 
  summarize(item_count = n()) %>% 
  arrange(desc(item_count))
```

There are 134 aisles, and the most items are ordered from the `fresh
vegetables` and `fresh fruits` aisles.

``` r
aisle_plot = aisle_df %>%
  filter(item_count >= 10000) %>% 
  mutate(aisle = fct_reorder(aisle, item_count)) %>% 
  ggplot(aes(x = aisle, y = item_count)) +
    geom_bar(stat = "identity", fill = "pink") +
    coord_flip() +
    labs(title = "Count of items ordered by aisle (10,000 minimum)")

aisle_plot
```

![](p8105_hw3_fw2334_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

Fruits and vegetables were by far the most ordered products, followed by
yogurt. All other products were ordered fewer than 50,000
times.

### Table: Three most popular items in baking ingredients, dog food care, and packaged vegetables fruits aisles

``` r
aisles_table = instacart %>%
  filter(aisle == "baking ingredients" | aisle == "dog food care" | aisle == "packaged vegetables fruits") %>% 
  group_by(aisle, product_name) %>% 
  summarize(product_name_count = n()) %>% 
  mutate(product_rank = rank(-product_name_count)) %>% 
  filter(product_rank <= 3) %>% 
  mutate(product_info = paste(product_name, product_name_count, sep = ", n = ")) %>% 
  select(-product_name, -product_name_count) %>% 
  pivot_wider(
    names_from = aisle,
    values_from = product_info) %>% 
  arrange(product_rank)

knitr::kable(aisles_table)
```

| product\_rank | baking ingredients         | dog food care                                         | packaged vegetables fruits     |
| ------------: | :------------------------- | :---------------------------------------------------- | :----------------------------- |
|             1 | Light Brown Sugar, n = 499 | Snack Sticks Chicken & Rice Recipe Dog Treats, n = 30 | Organic Baby Spinach, n = 9784 |
|             2 | Pure Baking Soda, n = 387  | Organix Chicken & Brown Rice Recipe, n = 28           | Organic Raspberries, n = 5546  |
|             3 | Cane Sugar, n = 336        | Small Dog Biscuits, n = 26                            | Organic Blueberries, n = 4966  |

The top ranking products in the `baking ingredients`, `dog food care`,
and `packaged vegetable fruits` aisles were Light Brown Sugar (n = 499),
Snack Sticks Chicken & Rice Recip Dog Treats (n = 30), and Organic Baby
Spinach (n = 9784),
respectively.

### Table: Pink Lady Apples and Coffee Ice Cream: mean time of day ordered

``` r
apples_icecream_table = instacart %>% 
  select(product_name, order_dow, order_hour_of_day) %>% 
  filter(product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream") %>% 
  mutate(order_day = as.numeric(order_dow)) %>% 
  group_by(product_name, order_day) %>% 
  mutate(mean_hour = mean(order_hour_of_day)) %>% 
  select(-order_hour_of_day, -order_dow) %>% 
  distinct() %>% 
  pivot_wider(
    names_from = product_name,
    values_from = mean_hour) %>% 
  arrange(order_day) %>% 
  separate("Pink Lady Apples", c("apples_hr", "apples_min"), 2) %>% 
  separate("Coffee Ice Cream", c("icecream_hr", "icecream_min"), 2) %>% 
  mutate(
    apples_minute = round(as.numeric(apples_min)*60),
    ice_cream_minute = round(as.numeric(icecream_min)*60),
    pink_lady_apples = paste(apples_hr, apples_minute, sep = ":"),
    coffee_ice_cream = paste(icecream_hr, ice_cream_minute, sep = ":")) %>% 
  select(order_day, pink_lady_apples, coffee_ice_cream)

knitr::kable(apples_icecream_table)
```

| order\_day | pink\_lady\_apples | coffee\_ice\_cream |
| ---------: | :----------------- | :----------------- |
|          0 | 13:26              | 13:46              |
|          1 | 11:22              | 14:19              |
|          2 | 11:42              | 15:23              |
|          3 | 14:15              | 15:19              |
|          4 | 11:33              | 15:13              |
|          5 | 12:47              | 12:16              |
|          6 | 11:56              | 13:50              |

Coffee ice cream was on average ordered later in the day than pink lady
apples.

# Problem 2

``` r
data("brfss_smart2010")

brfss_cleaned = brfss_smart2010 %>% 
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>% 
  mutate(
    response_f = as.factor(response),
    response_ordered = ordered(response_f, levels = c("Poor", "Fair", "Good", "Very good", "Excellent"))) %>% 
  separate(locationdesc, c("state", "county"), " - ") %>% 
  select(-locationabbr, -response_f)
```

``` r
brfss_7locations = brfss_cleaned %>% 
  group_by(year, state) %>% 
  summarize(location_count = n_distinct(county)) %>% 
  filter((year == "2002" | year == "2010") & location_count >= 7)
```

#### States observed at 7 or more locations:

  - In 2002, the states with 7 or more distinct locations were CT, FL,
    MA, NC, NJ, PA.
  - In 2010, The states with 7 or more dinstinct locations were CA, CO,
    FL, MA, MD, NC, NE, NJ, NY, OH, PA, SC, TX, WA.

<!-- end list -->

``` r
brfss_excellent = brfss_cleaned %>% 
  filter(response == "Excellent") %>% 
  select(year, state, data_value) %>% 
  group_by(year, state) %>% 
  summarize(mean_value = mean(data_value, na.rm = TRUE)) %>%
  ggplot(aes(x = year, y = mean_value, group = state, color = state)) +
    geom_line() +
    labs(title = "Mean data value over time by state")

brfss_excellent
```

![](p8105_hw3_fw2334_files/figure-gfm/unnamed-chunk-8-1.png)<!-- -->

``` r
brfss_ny = brfss_cleaned %>% 
  filter(
    state == "NY",
    year == "2006" | year == "2010") %>% 
  select(year, state, response_ordered, data_value) %>% 
  group_by(year, response_ordered) %>% 
  ggplot(aes(x = response_ordered, y = data_value)) +
    geom_point() +
    facet_grid(~year) +
    labs(title = "Data value distribution across response types for overall health in New York")

brfss_ny
```

![](p8105_hw3_fw2334_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->

The distribution of overall health was similar comparing 2006 and 2010
data. One notable difference is that “Very good” responses were more
prevalent in 2010 compared to 2006.

# Problem 3

``` r
accel_df = read_csv(file = "./data/accel_data.csv") %>% 
  janitor::clean_names() %>% 
   pivot_longer(
    activity_1:activity_1440,
    names_to = "minute",
    values_to = "activity_time") %>% 
  mutate(
    day_type = ifelse(day == "Saturday" | day == "Sunday", "weekend", "weekday"),
    day_f = as.factor(day),
    day_ordered = ordered(
      day_f, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")),
    minute = substr(minute, 10, nchar(minute)),
    minute_of_day = as.numeric(minute)) %>%
  select(-day_f, -day, -minute)
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_double(),
    ##   day = col_character()
    ## )

    ## See spec(...) for full column specifications.

#### Description of dataset

This dataset has 50400 observations and 6 variables. Each row of data
relates to a minute of the day, and variables include `week`, `day_id`
(i.e. day 1, day 2, etc.), `day_ordered` (i.e. Monday, Tuesday, etc.),
`day_type` (weekend vs. weekday), and `activity_time` calculated by the
accelerometer.

### Table: Total activity by day

``` r
accel_total = accel_df %>% 
  group_by(day_id) %>% 
  summarize(total_activity = sum(activity_time, na.rm = TRUE))

knitr::kable(accel_total)
```

| day\_id | total\_activity |
| ------: | --------------: |
|       1 |       480542.62 |
|       2 |        78828.07 |
|       3 |       376254.00 |
|       4 |       631105.00 |
|       5 |       355923.64 |
|       6 |       307094.24 |
|       7 |       340115.01 |
|       8 |       568839.00 |
|       9 |       295431.00 |
|      10 |       607175.00 |
|      11 |       422018.00 |
|      12 |       474048.00 |
|      13 |       423245.00 |
|      14 |       440962.00 |
|      15 |       467420.00 |
|      16 |       685910.00 |
|      17 |       382928.00 |
|      18 |       467052.00 |
|      19 |       371230.00 |
|      20 |       381507.00 |
|      21 |       468869.00 |
|      22 |       154049.00 |
|      23 |       409450.00 |
|      24 |         1440.00 |
|      25 |       260617.00 |
|      26 |       340291.00 |
|      27 |       319568.00 |
|      28 |       434460.00 |
|      29 |       620860.00 |
|      30 |       389080.00 |
|      31 |         1440.00 |
|      32 |       138421.00 |
|      33 |       549658.00 |
|      34 |       367824.00 |
|      35 |       445366.00 |

Activity seems to go up and then back down over the course of weeks (up
for a few days and then back down), but it is difficult to see a clear
pattern by looking at this table.

### Plot: Activity over each 24 hour period

``` r
accel_24hr = accel_df %>% 
  ggplot(aes(x = minute_of_day, y = activity_time, group = day_id, color = day_ordered)) +
    geom_smooth() +
    labs(title = "Activity over the course of each day") +
    scale_x_continuous(breaks = seq(from = 0, to = 1440, by = 100))

accel_24hr
```

    ## `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'

![](p8105_hw3_fw2334_files/figure-gfm/unnamed-chunk-12-1.png)<!-- -->

One clear pattern in the data is that on Sundays, the man is typically
more active earlier in the day and not very active towards the end of
the day. This is different from other days, when activity is more varied
and there tends to be a fair amount of activity towards the end of the
24 hour period.
